apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://lakshit175_db_user:7XkXrXDAbK11ADMx@lukkytutedude.xhmdblx.mongodb.net/?appName=LukkyTuteDude"